import type { InventoryItem, Branch } from './types';

export const INITIAL_INVENTORY: InventoryItem[] = [
    { id: 1, name: 'A4 Paper- Dark Blue (80 gram)/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 2, name: 'A4 Paper- Light Blue (80 gram)/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 3, name: 'A4 Paper- Light Green (80 gram)/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 4, name: 'A4 Paper- Orange (80 gram)/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 5, name: 'A4 Paper- Pink (80 gram)/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 6, name: 'A4 Paper- Red (80 gram)/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 7, name: 'A4 Paper- Yellow (80 gram)/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 8, name: 'AA batteries energizer/pcs', brand: 'Energizer', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Electronics' },
    { id: 9, name: 'AAA batteries energizer/pcs', brand: 'Energizer', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Electronics' },
    { id: 10, name: 'Acrylic 12ml *12', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Art Supplies' },
    { id: 11, name: 'brushers big (pack)', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Art Supplies' },
    { id: 12, name: 'binder clips', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 13, name: 'Black Pen/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 14, name: 'Blue Pen/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 15, name: 'blue pens/ pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 16, name: 'Board Eraser/pack (stanger)', brand: 'Stanger', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 17, name: 'Board markers Black/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 18, name: 'Board markers Blue/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 19, name: 'Board markers Green/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 20, name: 'Board markers Red/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 21, name: 'Construction Paper (beige) 70*100', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 22, name: 'Construction paper (Black) 100*70 /pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 23, name: 'Construction paper (Brown) 100*70 /pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 24, name: 'Construction paper (Dark Blue) 100*70/pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 25, name: 'Construction paper (Dark Green) 100*70/pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 26, name: 'Construction paper (Light Blue) 100*70/pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 27, name: 'Construction paper (Light Green) 100*70 /pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 28, name: 'Construction paper (Orange) 100*70 /pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 29, name: 'Construction paper (Pink) 100*70 /pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 30, name: 'Construction Paper (purple) 70*100', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 31, name: 'Construction paper (Red) 100*70 /pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 32, name: 'Construction paper (White) 100*70 /pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 33, name: 'Construction paper (Yellow) 100*70 /pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 34, name: 'Colored Beads 500 gm', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 35, name: 'Colored Playdough 12 pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 36, name: 'Colour Pencil /pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 37, name: 'Dice', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 38, name: 'Envelope A3', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 39, name: 'Envelope A4', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 40, name: 'Envelope C5', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 41, name: 'Envelope C6', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 42, name: 'Eraser or rubber (small) /pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 43, name: 'Felt tip colour / pack (Jumbo)', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 44, name: 'File with button', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 45, name: 'fly swat/pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Other' },
    { id: 46, name: 'foam balls (the large size)/pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 47, name: 'Glue Gun - Big one', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 48, name: 'Glue Gun - Small one', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 49, name: 'Glue Gun stick /pack (Thick)', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 50, name: 'Glue stick/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 51, name: 'Green Pen/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 52, name: 'highlighter (green)', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 53, name: 'highlighter (orange)', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 54, name: 'highlighter (pink)', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 55, name: 'highlighter (yellow)', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 56, name: 'Lamination Sheet A3 /pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 57, name: 'Lamination Sheet A4 /pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 58, name: 'Magic Tape / pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 59, name: 'Mini White Board/pcs (A5) - Think ones - Plain (metal)', brand: 'Think ones', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 60, name: 'Paint Brushes size 3', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Art Supplies' },
    { id: 61, name: 'paper A3 / per box', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 62, name: 'paper A4 / per box', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Paper' },
    { id: 63, name: 'Paper Clip (33mm)/Box', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 64, name: 'pencil / pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 65, name: 'Pencil case', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 66, name: 'Pipe Cleaners-1 piece', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 67, name: 'Plastic Straws-pck 50 pcs', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 68, name: 'plastic wallet (A4)/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 69, name: 'Red pen/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 70, name: 'red pens/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Writing' },
    { id: 71, name: 'Ruler 20 cm / pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 72, name: 'Sacco U-shape pck of 100', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 73, name: 'Safty Scissors', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 74, name: 'Sharpeners /pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 75, name: 'shish tawook sticks /pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 76, name: 'Small brushes (pack)', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Art Supplies' },
    { id: 77, name: 'Small Paper plates - pack of 10', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 78, name: 'squishy stress balls/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Toys' },
    { id: 79, name: 'Stickers sheet stars shapes/pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 80, name: 'Sticky Notes A5', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 81, name: 'Tongue Depressors', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' },
    { id: 82, name: 'transprent pencil case', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Stationery' },
    { id: 83, name: 'Water colours', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Art Supplies' },
    { id: 84, name: 'Crayons /pack', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Art Supplies' },
    { id: 85, name: 'wide tape/pcs (4-5 cm)', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Office' },
    { id: 86, name: 'wooden coloured pegs - small sized', brand: 'Generic', agouza: 0, heliopolis: 0, oct: 0, alex: 0, cityStars: 0, cat: 'Crafts' }
];


export const BRANCHES: Branch[] = [
    { key: 'agouza', name: 'Agouza', bg: 'bg-purple-600', light: 'bg-purple-50', border: 'border-purple-600', dark: 'bg-purple-800', text: 'text-purple-600', abbreviation: 'AGZ' },
    { key: 'heliopolis', name: 'Heliopolis', bg: 'bg-green-600', light: 'bg-green-50', border: 'border-green-600', dark: 'bg-green-800', text: 'text-green-600', abbreviation: 'HEL' },
    { key: 'oct', name: '6th of Oct', bg: 'bg-blue-600', light: 'bg-blue-50', border: 'border-blue-600', dark: 'bg-blue-800', text: 'text-blue-600', abbreviation: 'OCT' },
    { key: 'alex', name: 'Alex', bg: 'bg-orange-600', light: 'bg-orange-50', border: 'border-orange-600', dark: 'bg-orange-800', text: 'text-orange-600', abbreviation: 'ALX' },
    { key: 'cityStars', name: 'City Stars', bg: 'bg-red-600', light: 'bg-red-50', border: 'border-red-600', dark: 'bg-red-800', text: 'text-red-600', abbreviation: 'CS' }
];